# Generated by Django 4.2.20 on 2025-04-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telepsych_sessions', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
