# Generated by Django 4.2.20 on 2025-04-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telepsych_sessions', '0006_sessionmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AddField(
            model_name='sessionmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sessionmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
