# Generated by Django 4.2.20 on 2025-04-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telepsych_sessions', '0008_sessiontypingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Name and phone number of emergency contact', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, help_text='Any relevant medical history or conditions'),
        ),
    ]
