# Generated by Django 4.2.20 on 2025-04-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telepsych_sessions', '0011_researchstudy_researchsurvey_studyparticipant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyparticipant',
            name='consent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
